Docu perun node
hyperledger-labs/perun-doc pull request #38
Opened 2020-12-10 08:41 UTC by anagha-ks

This gives an overall idea about perun-node project, its features, versions etc.

Relates to #25

2020-12-10 18:03 UTC, choeppler requested changes
As @danielksan81's [suggested](https://github.com/hyperledger-labs/perun-doc/pull/26#issuecomment-739752795), some parts of the structure seem to be addressing the entire Perun project (index.rst and introduction.rst). Some, of course, deal with the perun-node only (perun-node.rst, user.rst, developer.rst). I guess there are three options how to set up the base structure now:
 - leave as is, and refactor, when the need arises (e.g. if go-perun developer documentation is added)
 - prefix all node-related docs with "node_" or move those parts into a subdirectory node/ so the physical structure in the repo reflects the logical structure of the document. Then we'd have
```
perun-node.rst -> node/introduction.rst
user.rst -> node/user.rst,
developer.rst -> node/developer.rst
```
 -  Alternatively, we could have user and developer documentation as top-level structure (e.g. `developer.rst -> developer/node.rst`)

Thoughts?

2020-12-11 03:43 UTC, anagha-ks commented
> As @danielksan81's [suggested](https://github.com/hyperledger-labs/perun-doc/pull/26#issuecomment-739752795), some parts of the structure seem to be addressing the entire Perun project (index.rst and introduction.rst). Some, of course, deal with the perun-node only (perun-node.rst, user.rst, developer.rst). I guess there are three options how to set up the base structure now:
> 
>     * leave as is, and refactor, when the need arises (e.g. if go-perun developer documentation is added)
> 
>     * prefix all node-related docs with "node_" or move those parts into a subdirectory node/ so the physical structure in the repo reflects the logical structure of the document. Then we'd have
> 
> 
> ```
> perun-node.rst -> node/introduction.rst
> user.rst -> node/user.rst,
> developer.rst -> node/developer.rst
> ```
> 
>     * Alternatively, we could have user and developer documentation as top-level structure (e.g. `developer.rst -> developer/node.rst`)
> 
> 
> Thoughts?

Yes. The idea was like keep index.rst and introduction.rst for general purpose. since there were no documentation started from go-perun, i kept everything in the same folder structure.

But i think for other documentation can we include all node related documents in to one folder called `node`?
which means,

perun-node.rst -> node/introduction.rst 
user.rst -> node/user.rst
developer.rst -> node/developer.rst

2020-12-18 05:03 UTC, anagha-ks commented on source/index.rst
> -Link to the project on GitHub: https://github.com/hyperledger-labs?q=perun
Everything is updated now.

2020-12-18 17:08 UTC, manoranjith approved these changes

2020-12-18 17:55 UTC, choeppler approved these changes

2020-12-18 19:19 UTC, merged