Add node/index, move node/user guide to sep file
hyperledger-labs/perun-doc pull request #55
Opened 2021-04-02 09:34 UTC by manoranjith

- Adding an index page for node documentation allows different sections
  to be split into individual files.

- Move the user guide section into a separate file.

Closes #54

2021-04-05 09:58 UTC, anagha-ks requested changes

2021-04-05 09:58 UTC, anagha-ks commented on source/node/user_guide.rst
> +  When any one of the channel participant sends a channel close request to
```suggestion
  When any one of the channel participants sends a channel close request to
```

2021-04-06 06:07 UTC, manoranjith commented on source/node/user_guide.rst
> +1. The blockchain node was setup in step 1 and the perun-node binary was
Have revised this line in the latest commit.

2021-04-09 04:58 UTC, anagha-ks requested changes

2021-04-09 04:58 UTC, anagha-ks commented on source/node/user_guide.rst
> +   default configuration artifacts which we will be generate in later steps.
```suggestion
   default configuration artifacts which we will generate in later steps.
```

2021-04-09 04:58 UTC, anagha-ks commented on source/node/user_guide.rst
> +   We fund each of these accounts are with 10 ETH each.
```suggestion
   We fund each of these accounts with 10 ETH each.
```

2021-04-12 06:45 UTC, anagha-ks approved these changes

2021-04-13 06:48 UTC, merged